    ;do $System.OBJ.LoadDir("/home/irisowner/dev/src","ck",,1)

    ;disabling password expire for development purposes
    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")

    ; remove passwords for web applications for dev purposes
    zpm "install passwordless"
    ; importing the source code of the repository as ZPM module
    zn "USER"
    zpm "load /home/irisowner/dev -v":1:1
    halt
